#ifndef CHAMELEON__VERSION_H
#define CHAMELEON__VERSION_H

#define CHAMELEON_VERSION_MAJOR 0  
#define CHAMELEON_VERSION_MINOR 1
#define CHAMELEON_VERSION_BUILD 0

#define CHAMELEON_VERSION_STRING "0.1.0"

#endif // CHAMELEON__VERSION_H
